---
# This assigns a PR to its author
addAssignees: author

addReviewers: true

useReviewGroups: true

reviewGroups:
  maintainers:
    - reasonerjt
    - ywk253100
    - renmaosheng
    - wy65701436
    - steven-zou
    - Vad1mo
  community:
    - OrlinVasilev
  contributors:
    - stonezdj
    - chlins
    - zyyw
    - MinerYang
    - AllForNothing

options:
  ignore_draft: true
  ignored_keywords:
    - WIP
    - wip
    - DO NOT MERGE
  enable_group_assignment: true
  number_of_reviewers: 2