language: go

go: 
  - 1.6.2

#go_import_path: github.com/vmware/harbor

service: 
  - docker 

#env: DB_HOST=127.0.0.1 DB_PORT=3306 DB_USR=root DB_PWD=

install: 
  - docker-compose -f Deploy/docker-compose.yml up -d

#before_script:
  # create tables and load data
  #- mysql < ./Deploy/db/registry.sql -uroot --verbose


#script: 
#  - go list ./... | grep -v /vendor/ | xargs -L1 fgt golint
#  - go list ./... | grep -v 'vendor' | xargs -L1 go vet
#  - go list ./... | grep -v 'vendor' | xargs -L1 go test -v
