sudo: true
language: go
go:
- 1.9.2
go_import_path: github.com/goharbor/harbor
services:
- docker
dist: trusty
matrix:
  include:
  - go: 1.9.2
    env:
    - UTTEST=true
  - go: 1.9.2
    env:
    - APITEST_DB=true
  - go: 1.9.2
    env:
    - APITEST_LDAP=true
  - go: 1.9.2
    env:
    - OFFLINE=true
env:
  global:
  - POSTGRESQL_HOST: localhost
  - POSTGRESQL_PORT: 5432
  - POSTGRESQL_USR: postgres
  - POSTGRESQL_PWD: root123
  - POSTGRESQL_DATABASE: registry
  - ADMINSERVER_URL: http://127.0.0.1:8888
  - DOCKER_COMPOSE_VERSION: 1.22.0
  - HARBOR_ADMIN: admin
  - HARBOR_ADMIN_PASSWD: Harbor12345
  - CORE_SECRET: tempString
  - KEY_PATH: "/data/secretkey"
  - REDIS_HOST: localhost
  - REG_VERSION: v2.6.2
  - UI_BUILDER_VERSION: 1.6.0
  - secure: Vr95Mwikx3fl+0zHYVBRThomscSnCaNfI9EQ4ZjSPS1pPp32zOrJSP3Bcox8uMMey49D3fjAhVnGJN1sI06LHwmyOLfaPTFpg7Ih8cwfuu+rcm8w9KDHG5MHf/LJnEWxGeBrZUIdfizRY4nFivsuYCEMm/LE+NsiOlu8xJ95hTy6NC+LhflBoBHzsllq4zNFTl4UApxL2k5vbqB8LSgG/4c+VHTcqoYWZW+tamAOye11PsvwqJbeZ3Jr13fDPeShmoKBHcI14t+4h9x79Wb6fcSDCa0ZKb6OgdxPvay+uqlVJ7Kz5RXobmdJSRMLDhJmUB1Bc+xwj/Swy3NagDZT7LQDL49JmcGrAp976czvlZaYKFBHLqZX5KeBF36ooc4Elxx2KWS2BDjNAQIuKmomo0mSbLDbzmJ89B0TCC/HfjSl4B2vscqsMrHn/FWknJ7d8/BdLk0Q1TiisX24aWzyI/egY6Tsys4JMKw0ZxjkTXu5MAlOvhouL1Ozl2cjTb5Sijh2wrRStceDcV+Vqr+dzETxkRATjRr3Bn1jaUg1N5J1Cr1Mi74G+58jYO5mTFmUMAA4c+wZuKydVRIkVnvPA6IBAxjTmyFWCtW+/sjH2eeHloPAJATPgZ7doNh2bHJ0xvMYYQKI11h7DqxFROGv2TZIxBpSmxdzpQ86l0E0xEg=
  - secure: qcpl5/yOBH+Ea9tLmrRxMnH6aVDkGfPrll6Hj1fM24TY8ID+4RO4SHULmtgF43Y0FIkcQ552IZIimjncRIRWg7kExGIWfhD1dsWJT97oviYMXmmKJCS9yrec+gLaEBdYeHylCvq0IKQPDv7bo/cMwB63232DT4ez3sYxZrtz83D/5H+YZTSBOq0+7sZiS92a9e6jUcNmJL+36DGQhGeNCSgdF1bPF1cjnWoHpnVjuRqo7Yu1mqOq46Q1Z+URS5STpAOUY6+OtKEuwrkoFv7KK8N68DUae6mS4iu6aOpxM7dkgD7b4+zSDiqbjtryCXHXIor+tw4aS1EKxwrU4oPm3PEQHB0l+oo+tYwvO/Aj4LIv8Nqp07X5M3cR7DHuykVPeWeuBS4hpaSx7WkVoa0uLYm5zzCmo0M9YuJb2M2t7GS/KUhOoY++NXxCNhAxNL6vQFRl5a/YF2EIJLuIQIJnyu3vd/z8euuWRbVYqbG8jUYhDV2AF/L7ISNumhQxPnz/dLp1XJrM4D7WXBiMrszGRjXJrjh4RZ2W+BY6ct9zPIYA2zv3EJRmSB21y+ur1n6zvO5XC8Z2HYyw143H66sqrWIZu5ef8kY9uxoZsSdxzOgPonFYYm8sqXXefcUsSmV6F1NWOWda6bxMi+/NBEXsjfbveDAKdFUIbcunxPfq7bg=
  - secure: Y67tfRCnJvmJw3nO7XufV3JsyjYWaNyNkK5Wt/Z7aLN86aLcW1ILzYpLCqT+2MUo0qZ6y1kbPg35A+1VPGi5DJ9tiz07q92xxPjOlnGdTk6JuX/b8Gz+WpCU4pV3Wf1LvN/d8s7Iiv/d/cWr4uXIhcvg31ct5Qb95owWIdUXaDCUdw//inVbSMGbsx8R9Fq0uvqaU3kKDporAlSwBTSpvP0FsNLZCrFPsRCGnlZ+9/5IL1kr57MmJX2nJIJiWke+l0YuhDH0sxB3SFkO7/A8RPpZvctcRmz6ab4C/Wak461nrycvsF1QV/9s43EkKLjzX96qnAaqe4yMMkq+1nzioHNTx85KdameHbFytA23YWr8D1uJxtoUSkZkvcOItong9HvOjGmDXqmavnliYJ4rtc83opp2rD44PAfHgV86NWydMIWVe0FE2QB3+mxcefSKghHzah31Qh7ksefY3NTIBZgg8Iq9ZakTbB7oGgm6ZWAxaYbEqkaALpnmsmAIeZqGVrmAe0IUO+XQtwpqr6gG6yap5g4gAkNPM0oBiOlSmScV6kSKRO47+CLs50ajxrXKYZh1eCk6eNN5SLVC2cukYhTzhcbC11ZmkePC5NHWi66XNRmpc1ynQ1eZghYaVmEVCsP2p6YwvLtmbZG/Mfk3NF5klDCgbQlAQPG3H0kzmfE=
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- sudo rm -f /etc/boto.cfg
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- IP=`ip addr s eth0 |grep "inet "|awk '{print $2}' |awk -F "/" '{print $1}'`
- sudo sed -i '$a DOCKER_OPTS=\"--insecure-registry '$IP':5000\"' /etc/default/docker
- export IP=$IP
- sudo service docker restart
install:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  DB; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  LDAP; fi
script:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh $IP; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_run.sh DB $IP; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_run.sh LDAP $IP; fi
- if [ "$OFFLINE" == true ]; then bash ./tests/travis/distro_installer.sh; fi