sudo: true
language: go
go:
- 1.9.2
go_import_path: github.com/goharbor/harbor
services:
- docker
dist: trusty
matrix:
  include:
  - go: 1.9.2
    env:
    - UTTEST=true
  - go: 1.9.2
    env:
    - APITEST_DB=true
  - go: 1.9.2
    env:
    - APITEST_LDAP=true
  - go: 1.9.2
    env:
    - OFFLINE=true
env:
  global:
  - POSTGRESQL_HOST: localhost
  - POSTGRESQL_PORT: 5432
  - POSTGRESQL_USR: postgres
  - POSTGRESQL_PWD: root123
  - POSTGRESQL_DATABASE: registry
  - ADMINSERVER_URL: http://127.0.0.1:8888
  - DOCKER_COMPOSE_VERSION: 1.22.0
  - HARBOR_ADMIN: admin
  - HARBOR_ADMIN_PASSWD: Harbor12345
  - CORE_SECRET: tempString
  - KEY_PATH: "/data/secretkey"
  - REDIS_HOST: localhost
  - REG_VERSION: v2.6.2
  - UI_BUILDER_VERSION: 1.6.0
  - secure: pn3B/xvy/0k2IRe0SFi/MOtsbvAPY6Kuom7cZ6ffjltbcbTqAwo4oeDFy105fsxRsYid1Qtypf0UTSESmtB68rjIhNUzDvwcSxn25NAFp59aO2zB3prikNS4lI7sD2gvIrh/ylQ5WxTwyTWjxbh64EL6dVjcmIqAUOqYZuuYo3TC5x2u/HlMfpWaicTRib5Kq+SBh0s5gkRAkpchHgVYwR1XPk7VPbSRo4P112XKaWf5k0D38fMBFe6PhrsRVfazFfcvGEJkZhWMiV16BKyxe3uTtsZBtd1F7GcxCTqN1saUBiwFM6cL165Wpya7zNBxLxn1pR36IjtVMrv8PFSUlR3nRs9IehyXDI0Ehi9KD+1EZYiTdvUgm3YfZnZ2gBM+JAITMChrrTeDFRs8FVdeErxa3nkE7BiWSGQScg94m+f482gCAAeJGAKwIzW0KbS6SG6Hj6SBh1G921BP9pVlLk7FgO9Y0imXGTKMDfjGV0dFVm3xUBXt5PcAM2tATHaVfgFSRq0yJZdkD+GEk1mPpJsDVjZO8fJIS+mgrO64sM1gXJGlbsY9CAc5nD0X0g5mkgl4/flvsbBK8H7pLoE2JZUZIIto6/ebUONIR0jP+XfeDmDMX5roU4ddRAFnKzOqWsOd4Nz4RbacXDqdB4YIcRnz7tvENXJ4yViadVcFbU0=
  - secure: KZlqTuCTcgAAnYSTJC7wSLL+Mohva2YO5sAmEOK7bErcvnPcJIFwQ6Mt0B+a+cks/9a7IKdrhJugo1Dgmg/Af7Sd+HzFsTv5LfFoWp25+IYz5dZDi+viEv3WPc2t8zLvqe7/ExgniQZlgkHtYGWWtGquA+Xt2paZrj9Kgo7g6ZEYP7wA5+ow2Vw1jRBrCugRyB/nB3aEumGR+tQCfyutFheLzkm3vVOWg/DHuZYbbqNRNubgO+7Oln3OO3ZhpuOD2YJVP2018b+S7AKrlqyyYGfMMJ8NnhsKFb5D8tgUWRamEUAW8topu329QbwodPl0sDQewCgRvTZO13xJvfB+eo7McA1iT/j5TmyqfREWNvJ449YrUzlgt4eeEw4ICXaRds8XYU30xTF65EfPQmHvMxadWOFlIxuHj0AT/ej2FG8z+uBQ32jgPw6HR4lS3NBsitErm1QbvAGbZLzwRGETrwj5NyjuDlehtlJHs6S9IZC4sY5YtukvSen5Z65cg4NHtxWnZwgRugS+Wop2oXWkxCCDjpYZROJxTk9idJR8cXB+3wFpLlSQc11xSsHYindtYgyZ0+9aOumFavyk+ekVBY6/ZpwhJITp7eHT41HzT96ZKN9Lvlq7BI4B+9ber3LUlVNtQB22PWur+0KCSjb04PLTi+hGbssPpaeDJqxOZCw=
  - secure: DspkoCNFuIcU5p58pJzfteRSh21fvQlHRVJqO5ZoTK6/kr/ksDOChitWitZp8koLNR2jUZnE9iaur3onV1UirK0SPGy1iLZ8kAl8hk0v/fmrn9RMrdWPzCSFNa93yEnXGiOENpEjrXasX31IY5fxmF5m7eD3mSSOvT+LgI+07XIusTL2gqJlrN/If0dXOoqRKB850Q7TW2mmMufSmBBLRJqXXhuZXhJP1y/gdGClTgS5Szi1T3zVnHWHKHqWRpRWofK6y7Om642dU+zIeRlbGlF7TK5jMP3AoQz5BL1sgffDezS/V4jmxt5xYXVmOel1d4ENnSKhUpecWG3CCBEGvlb3aJ7+Tqi5ktvYkSRj9QW4AbJ9p4c+tDkG0kfR/7cmpbwO4xoUcx8lwIDFoheGnf79KLku1/8KdwZX01aHf6mGzAIzcWNFpD2Y0jMZz8c9RpOL0InQUyPgk2aDEJc/owcMV4edKyewNnwxracYEN1KxIeeQYxjOfAYW5Q7E6uy9k7QVGKJp9OQHjtJzybV6LzVLjDs5YP3+cw0RxFNK8yfTJpJDm9ZgDY8dpkbIxJgux8qbgM6B/HDB+UIhq7VysQTGvsUkQzan3hm4zAQRpM1Wf17XSnal7SUqq1MQ9K8tj69zH/plvk83VrVjFxo7B6aYqzF3msTvZ4LCr0K/Dw=
addons:
apt:
  sources:
  - google-chrome
  packages:
  - google-chrome-stable
  - google-chrome-beta
before_install:
- sudo rm -f /etc/boto.cfg
- curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname
  -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- IP=`ip addr s eth0 |grep "inet "|awk '{print $2}' |awk -F "/" '{print $1}'`
- sudo sed -i '$a DOCKER_OPTS=\"--insecure-registry '$IP':5000\"' /etc/default/docker
- export IP=$IP
- sudo service docker restart
install:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_install.sh ; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  DB; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_common_install.sh $IP
  LDAP; fi
script:
- if [ "$UTTEST" == true ]; then bash ./tests/travis/ut_run.sh $IP; fi
- if [ "$APITEST_DB" == true ]; then bash ./tests/travis/api_run.sh DB $IP; fi
- if [ "$APITEST_LDAP" == true ]; then bash ./tests/travis/api_run.sh LDAP $IP; fi
- if [ "$OFFLINE" == true ]; then bash ./tests/travis/distro_installer.sh; fi