sudo: true

language: go

go: 
  - 1.6.2

#go_import_path: github.com/vmware/harbor

services: 
  - docker 

#env: DB_HOST=127.0.0.1 DB_PORT=3306 DB_USR=root DB_PWD=

install: 
  - cd Deploy
  - ./prepare
  - docker-compose up -d



