apiVersion: v1
kind: ConfigMap
metadata:
  name: harbor-adminserver-config
data:
  DATABASE_TYPE: mysql
  MYSQL_DATABASE: registry
  MYSQL_HOST: mysql
  MYSQL_PORT: "3306"
  MYSQL_USR: root
  MYSQL_PWD: "{{db_password}}"
  REGISTRY_URL: http://registry:5000
  HARBOR_REG_URL: "{{hostname}}"
  HARBOR_ADMIN_PASSWORD: "{{harbor_admin_password}}"
  AUTH_MODE: "{{auth_mode}}"
  LDAP_URL: "{{ldap_url}}"
  LDAP_SEARCH_DN: "{{ldap_searchdn}}"
  LDAP_SEARCH_PWD: "{{ldap_search_pwd}}"
  LDAP_BASE_DN: "{{ldap_basedn}}"
  LDAP_FILTER: "{{ldap_filter}}"
  LDAP_UID: "{{ldap_uid}}"
  LDAP_SCOPE: "{{ldap_scope}}"
  LOG_LEVEL: debug
  LDAP_TIMEOUT: "30"
  UI_SECRET: "{{ui_secret}}"
  GODEBUG: netdns=cgo
  EXT_ENDPOINT: "{{ui_url}}"
  TOKEN_URL: http://ui
  SELF_REGISTRATION: "{{self_registration}}"
  VERIFY_REMOTE_CERT: "{{verify_remote_cert}}"
  TOKEN_EXPIRATION: "{{token_expiration}}"
  PROJECT_CREATION_RESTRICTION: "{{project_creation_restriction}}"
  MAX_JOB_WORKERS: "{{max_job_workers}}"
  EMAIL_PWD: "{{email_password}}"
  EMAIL_PORT: "{{email_server_port}}"
  EMAIL_HOST: "{{email_server}}"
  EMAIL_FROM: "{{email_from}}"
  EMAIL_USR: "{{email_username}}"
  EMAIL_IDENTITY: "{{email_identity}}"
  EMAIL_SSL: "{{email_ssl}}"
  ADMIRAL_URL: NA
  SECRET_KEY: "{{secret_key}}"
  WITH_NOTARY: "false"
  config: |
    {
      "admin_initial_password": "{{harbor_admin_password}}",
      "admiral_url": "NA",
      "auth_mode": "{{auth_mode}}",
      "cfg_expiration": 5,
      "database_type": "mysql",
      "email_from": "{{email_from}}",
      "email_host": "{{email_server}}",
      "email_identity": "{{email_identity}}",
      "email_password": "{{email_password}}",
      "email_port": {{email_server_port}},
      "email_ssl": {{email_ssl}},
      "email_username": "{{email_username}}",
      "ext_endpoint": "{{ui_url}}",
      "ldap_base_dn": "{{ldap_basedn}}",
      "ldap_filter": "{{ldap_filter}}",
      "ldap_scope": {{ldap_scope}},
      "ldap_search_dn": "{{ldap_searchdn}}",
      "ldap_search_password": "{{ldap_search_pwd}}",
      "ldap_timeout": {{ldap_timeout}},
      "ldap_uid": "{{ldap_uid}}",
      "ldap_url": "{{ldap_url}}",
      "max_job_workers": {{max_job_workers}},
      "mysql_database": "registry",
      "mysql_host": "mysql",
      "mysql_password": "{{db_password}}",
      "mysql_port": 3306,
      "mysql_username": "root",
      "project_creation_restriction": "{{project_creation_restriction}}",
      "registry_url": "http://registry:5000",
      "self_registration": {{self_registration}},
      "sqlite_file": "",
      "token_expiration": {{token_expiration}},
      "verify_remote_cert": {{verify_remote_cert}},
      "with_notary": false
    }
  pkey: |
    {{4 auth_pkey}}
