apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jobservice
  labels:
    app: jobservice
spec:
  replicas: {{ .Values.jobservice.replicas }}
  template:
    metadata:
      labels:
        app: jobservice
    spec:
      containers:
      - name: jobservice
        image: {{ .Values.jobservice.image.repository }}:{{ .Values.jobservice.image.tag }}
        env:
          - name: UI_SECRET
            valueFrom:
              secretKeyRef:
                name: ui-secrets
                key: UI_SECRET
          - name: JOBSERVICE_SECRET
            valueFrom:
              secretKeyRef:
                name: jobservice-secrets
                key: JOBSERVICE_SECRET
          - name: LOG_LEVEL
            value: {{ .Values.jobservice.logLevel }}
          - name: CONFIG_PATH
            value: /etc/jobservice/app.conf
          - name: GODEBUG
            value: netdns=cgo
        imagePullPolicy: {{ .Values.jobservice.pullPolicy }}
        ports:
        - containerPort: {{ .Values.jobservice.containerPort | default 80 }}
        volumeMounts:
        - name: jobservice-config
          mountPath: /etc/jobservice/app.conf
          subPath: app.conf
        - name: jobservice-secrets
          mountPath: /etc/jobservice/key
          subPath: key
        - name: job-logs
          mountPath: /var/log/jobs
      volumes:
      - name: jobservice-config
        configMap:
          name: jobservice-config
      - name: jobservice-secrets
        secret:
          secretName: jobservice-secrets
          items:
            - key: key
              path: key
      - name: job-logs
        emptyDir: {}
