apiVersion: v1
kind: Secret
metadata:
  name: registry-secrets
type: Opaque
data:
  http-secret: {{ .Values.registry.httpSecret | b64enc }}
  gcs_keyfile.json: {{ .Values.registry.gcsKeyFile | b64enc }}
  root.crt: {{ .Values.rootCert | b64enc }}
