apiVersion: v1
kind: Secret
metadata:
  name: ui-secrets
type: Opaque
data:
  UI_SECRET: {{ .Values.ui.secret | b64enc }}
  key: {{ .Values.sharedKey | b64enc }}
  private_key.pem: {{ .Values.privateKey | b64enc }}
