{{ if .Values.ingress.enabled  }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress-ui-notary"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
spec:
{{ if not .Values.insecureRegistry }}
  tls:
  - hosts:
    - "{{ .Values.externalDomain }}"
    - "{{ template "harbor.notaryFQDN" . }}"
    secretName: "{{ template "harbor.fullname" . }}-ingress"
{{ end }}
  rules:
  - host: "{{ .Values.externalDomain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.fullname" . }}-ui
          servicePort: 80
  - host: "{{ template "harbor.notaryFQDN" . }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "harbor.notaryServiceName" . }}
          servicePort: 4443

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ template "harbor.fullname" . }}-ingress-registry"
  labels:
{{ include "harbor.labels" . | indent 4 }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{ if not .Values.nginx.enabled }}
    {{ .Values.ingress.rewriteAnnotation }}: /registryproxy/v2
{{ end }}
spec:
{{ if not .Values.insecureRegistry }}
  tls:
  - hosts:
    - "{{ .Values.externalDomain }}"
    secretName: "{{ template "harbor.fullname" . }}-ingress"
{{ end }}
  rules:
  - host: "{{ .Values.externalDomain }}"
    http:
      paths:
      - path: /v2
        backend:
          serviceName: {{ template "harbor.fullname" . }}-{{ if .Values.nginx.enabled }}nginx{{ else }}ui{{ end }}
          servicePort: 80


{{ end }}